### ISSUE TITLE
using NBA endpoints with AJAX

### ISSUE THREAD

**Issue by jmanian** [bttmly/nba#49]
Apologies in advance since this isn't an issue with this js client, but just an issue with using the NBA APIs more generally.

I'm trying to build a simple site that uses some of the NBA endpoints via AJAX, and I'm running into CORS issues. Basically I'm trying to use jQuery to retrieve some data from stats.nba.com and data.nba.com (e.g. https://data.nba.net/10s/prod/v1/2017/playoffsBracket.json). The problem I'm running into is that the response headers don't include `Access-Control-Allow-Origin`, so the browser refuses it.

The part that's confusing to me is that on nba.com it's seemingly doing the exact same thing but in that case the response headers include `Access-Control-Allow-Origin: *`. E.g. on [this page](http://www.nba.com/playoffs/2018/westseries2#/).

In the readme here it says that this works for the browser or Node, so I'm wondering if you have a solution for this problem. Is there some way to get the API to return `Access-Control-Allow-Origin: *` in the response header so that I can call it with AJAX?

**Comment by bttmly** [comment]
I believe the issue is that NBA's backend is checking some request header before it sets `Access-Control-Allow-Origin` response header. I'm pretty sure it checks either `Referer` or `Host` (or both) on the request, which I think are protected headers that you won't be able to set in the browser unfortunately. You'll probably need either a server application to make the requests (rather than through the browser directly) or set up some kind of proxy server.

**Comment by jmanian** [comment]
Thanks @bttmly, I believe you're right. I did some more poking at the endpoints with `curl` and it seems to be the case. I was able to set up a serverless proxy with AWS API Gateway, which allows you to do CORS headers and such.

So maybe the readme shouldn't say "for the browser or Node" since it seems it won't work in the browser?

**Comment by bttmly** [comment]
Some endpoints do work in the browser – clone the repo and run `make browser-test` to see this in action.

**Comment by jmanian** [comment]
Got it, thanks.
