### ISSUE TITLE
Make stats endpoints https

### ISSUE THREAD

**Issue by jacobwise** [bttmly/nba#60]
Can you make the stats.nba.com endpoints https? I'd be happy to do a PR if you want to add me as a contributor.

**Comment by bttmly** [comment]
The endpoints are configured here: https://github.com/bttmly/nba-client-template/blob/master/nba.json, PR welcome. You don't need to be a contributor to open a pull request. Perhaps we can remove the hard-coded protocol entirely and make it configurable. However, if your issue is that you're trying to use these in the browser from an `https` website, I don't think changing it to `http` won't help you – if I recall correctly, CORS is not supported on these endpoints.

**Comment by bttmly** [comment]
@jacobwise if you want to open a PR please do it in [this repo](https://github.com/bttmly/nba-client-template), I'm going to close this issue.
