### ISSUE TITLE
Defense Tracking

### ISSUE THREAD

**Issue by dtkavana** [bttmly/nba#63]
Do you have any idea why 
NBA.stats.playerTracking({ PtMeasureType: "Defense" });
would be returning different data than you will find via https://stats.nba.com/player/201143/defense-dash/?Season=2018-19&SeasonType=Regular%20Season.

I used Al Horford as an example: 
**Via the above call**
defRimFgPct: 0.564
defRimFga: 6.1
defRimFgm: 3.4

**Via stats.nba.com**
defRimFgPct: 0.552
defRimFga: 7.4
defRimFgm: 4.1

Both return the same number of games played.

Thanks

**Comment by bttmly** [comment]
No idea except that `playerTracking` uses a different endpoint (http://stats.nba.com/stats/leaguedashptstats). I've seen some comments lately that some of the older endpoints seem to have delayed data (https://github.com/bttmly/nba/issues/55). I'd accept a PR to add this `defense-dash` endpoint but its a bit of a different format from how all the other stats endpoints are currently constructed – notice that the player id is in the path rather than the query parameters. FWIW the stats endpoints in this package are generated dynamically by a JSON file you can find here https://github.com/bttmly/nba-client-template
